version: "3.8"

services:
  database:
    container_name: web2-database
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: web2
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./databasepg:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U admin -d web2" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    build: .
    container_name: web2-migrate
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://admin:admin@database:5432/web2
    command: >
      sh -c "
      echo 'Running migrations...' &&
      alembic upgrade head &&
      echo 'Running seed...' &&
      python -m app.db.seed &&
      echo 'Migrate one'"

  scanner:
    build: .
    container_name: web2-student-scanner
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./app/deployment/data:/app/app/deployment/data
      - ./data/submissions:/app/data/submissions
      - ./data/security_scan_results:/app/data/security_scan_results
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SNYK_TOKEN: ${SNYK_TOKEN}
      SUBMISSIONS_DIR: /app/data/submissions
      RESULTS_DIR: /app/data/security_scan_results
      HOST_DATA_DIR: ${HOST_DATA_DIR}
      DOCKER_HOST: unix:///var/run/docker.sock

      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: web2
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
    env_file:
      - .env
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      database:
        condition: service_healthy
