"""add updateeddate_deleteddate_classsroommember

Revision ID: 0da2810179bb
Revises: ba1e112e2676
Create Date: 2026-03-20 04:47:12.432530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0da2810179bb'
down_revision: Union[str, Sequence[str], None] = 'ba1e112e2676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('assignments', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('assignments', 'language_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('classroom_members', sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('classroom_members', sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classroom_members', 'deleted_date')
    op.drop_column('classroom_members', 'updated_date')
    op.alter_column('assignments', 'language_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assignments', 'due_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('assignments', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
