"""delete_assignment_project_relation

Revision ID: 596f0b54c7ba
Revises: e1b31aeaa4f6
Create Date: 2026-03-24 00:54:23.779619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596f0b54c7ba'
down_revision: Union[str, Sequence[str], None] = 'e1b31aeaa4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
