"""correctgrouprelation

Revision ID: 6d58628cade3
Revises: 0da2810179bb
Create Date: 2026-03-23 18:56:50.139520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d58628cade3'
down_revision: Union[str, Sequence[str], None] = '0da2810179bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('assignment_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('groups_project_id_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'assignments', ['assignment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('groups', 'project_id')
    op.add_column('projects', sa.Column('group_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('projects_assignment_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('projects', 'assignment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_assignment_id_fkey'), 'projects', 'assignments', ['assignment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('projects', 'group_id')
    op.add_column('groups', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_project_id_fkey'), 'groups', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('groups', 'assignment_id')
    # ### end Alembic commands ###
