"""add column is_approve and delete LOC

Revision ID: 770b474dd953
Revises: 28bc6d46d68f
Create Date: 2026-02-10 17:40:50.106445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '770b474dd953'
down_revision: Union[str, Sequence[str], None] = '28bc6d46d68f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_outcomes_id'), table_name='learning_outcomes')
    op.drop_table('learning_outcomes')
    op.add_column('classrooms', sa.Column('learning_out_come', sa.String(), nullable=True))
    op.alter_column('classrooms', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('teachers', sa.Column('is_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'is_approved')
    op.alter_column('classrooms', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('classrooms', 'learning_out_come')
    op.create_table('learning_outcomes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('classroom_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('learning_outcomes_classroom_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('learning_outcomes_pkey'))
    )
    op.create_index(op.f('ix_learning_outcomes_id'), 'learning_outcomes', ['id'], unique=False)
    # ### end Alembic commands ###
