"""create classrooms table

Revision ID: ae17b3f6a425
Revises: 770b474dd953
Create Date: 2026-02-17 10:48:31.785914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae17b3f6a425'
down_revision: Union[str, Sequence[str], None] = '770b474dd953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classrooms', sa.Column('learningoutcomes', sa.String(), nullable=True))
    op.drop_column('classrooms', 'learning_out_come')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classrooms', sa.Column('learning_out_come', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('classrooms', 'learningoutcomes')
    # ### end Alembic commands ###
