"""add timezone to datetime

Revision ID: ba1e112e2676
Revises: 5e593d2edd4d
Create Date: 2026-02-27 04:51:37.339020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba1e112e2676'
down_revision: Union[str, Sequence[str], None] = '5e593d2edd4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('assignments', 'start_date',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('now()'))
    # op.alter_column('assignments', 'due_date',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=False)
    # op.alter_column('assignments', 'language_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    
    op.execute("""
        INSERT INTO project_types (id, name)
        VALUES
            (1, 'FE'),
            (2, 'BE'),
            (3, 'Project')
        ON CONFLICT (id) DO NOTHING;
    """)

    # 🔹 Seed languages (JPlag supported)
    op.execute("""
        INSERT INTO languages (id, name)
        VALUES
            (1, 'Java'),
            (2, 'Python'),
            (3, 'C'),
            (4, 'C++'),
            (5, 'JavaScript'),
            (6, 'TypeScript'),
            (7, 'Go'),
            (8, 'Kotlin'),
            (9, 'Swift'),
            (10, 'Rust')
        ON CONFLICT (id) DO NOTHING;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'language_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assignments', 'due_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('assignments', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
