"""init

Revision ID: dfa493f88ce3
Revises: 
Create Date: 2026-05-03 00:41:46.896142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa493f88ce3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_of',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'student_id', name='uq_project_student')
    )
    op.create_index(op.f('ix_submission_of_id'), 'submission_of', ['id'], unique=False)
    op.drop_index(op.f('ix_projects_project_uuid'), table_name='projects')
    op.drop_column('projects', 'project_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_uuid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_projects_project_uuid'), 'projects', ['project_uuid'], unique=True)
    op.drop_index(op.f('ix_submission_of_id'), table_name='submission_of')
    op.drop_table('submission_of')
    # ### end Alembic commands ###
