"""change project to store studentId

Revision ID: e1bce97de807
Revises: 9b3cd69b774a
Create Date: 2026-04-15 16:32:21.112778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1bce97de807'
down_revision: Union[str, Sequence[str], None] = '9b3cd69b774a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_of_id'), table_name='submission_of')
    op.drop_table('submission_of')
    op.add_column('projects', sa.Column('student_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('container_id', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('container_resource', sa.String(), nullable=True))
    op.alter_column('projects', 'project_source_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'projects', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'project_source_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('projects', 'container_resource')
    op.drop_column('projects', 'container_id')
    op.drop_column('projects', 'student_id')
    op.create_table('submission_of',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('submission_of_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('submission_of_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('submission_of_pkey')),
    sa.UniqueConstraint('project_id', 'student_id', name=op.f('uq_project_student'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_submission_of_id'), 'submission_of', ['id'], unique=False)
    # ### end Alembic commands ###
