"""Project analysis orchestrator — uses LLM + AST code parsing."""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import Any, Dict

from app.deployment.core.exceptions import AnalysisError
from app.deployment.models.project import ProjectAnalysis
from app.deployment.services.analyzer.code_parser import parse_project_code
from app.deployment.services.analyzer.file_scanner import build_file_tree, sample_key_files
from app.deployment.services.llm.client import llm_client
from app.deployment.services.llm.parser import extract_json
from app.deployment.services.llm.prompts import ANALYSIS_SYSTEM, ANALYSIS_USER

logger = logging.getLogger(__name__)


async def analyze_project(project_path: str, hint_type: str | None = None) -> ProjectAnalysis:
    """Analyse a project directory and return a structured analysis.

    Steps:
    1. Scan files and build context
    2. Run AST / regex code parser (endpoints, UI elements, components)
    3. Try LLM analysis (using hint_type if provided)
    4. Merge code-parser results into backend_info
    """
    root = Path(project_path)
    if not root.exists():
        raise AnalysisError(f"Project path does not exist: {project_path}")

    logger.info("Analysing project: %s", root.name)

    # 1. Scan
    file_tree = build_file_tree(root)
    file_samples = sample_key_files(root)

    tree_str = json.dumps(file_tree, indent=2, ensure_ascii=False)
    samples_str = "\n\n".join(
        f"### {path}\n```\n{content}\n```"
        for path, content in file_samples.items()
    )

    # 2. AST / regex code parsing (fast, no LLM)
    parsed_code: Dict[str, Any] = {}
    try:
        parsed_code = parse_project_code(root)
        ep_count = parsed_code.get("summary", {}).get("total_api_endpoints", 0)
        ui_count = parsed_code.get("summary", {}).get("total_ui_elements", 0)
        logger.info("Code parser finished: %d endpoints, %d UI elements found", ep_count, ui_count)
        if ep_count > 0:
            logger.info("Code parser endpoints: %s", [ep.get('path') for ep in parsed_code.get('api_endpoints', [])])
    except Exception as exc:
        logger.warning("Code parser error (non-fatal): %s", exc)

    # 3. Try LLM
    analysis: ProjectAnalysis | None = None
    try:
        user_prompt = ANALYSIS_USER.format(
            file_tree=tree_str,
            file_samples=samples_str,
            hint_type=hint_type or "auto-detect",
        )
        result = await llm_client.analyze_json(ANALYSIS_SYSTEM, user_prompt)
        if result:
            analysis = ProjectAnalysis.model_validate(result)
            logger.info(
                "LLM analysis complete: type=%s, stack=%s",
                analysis.project_type, analysis.tech_stack,
            )
    except Exception as exc:
        logger.warning("LLM analysis failed: %s", exc)

    # 4. Fallback heuristic if LLM analysis fails
    if analysis is None:
        logger.warning("LLM analysis failed, falling back to heuristic analysis")
        analysis = ProjectAnalysis(summary="Generated by heuristic fallback")
        
        # Check files
        files = []
        if file_tree and file_tree.get("children"):
            def _gather(n, curr_path=""):
                if n.get("type") == "file":
                    files.append(n.get("path", ""))
                elif n.get("children"):
                    for c in n.get("children"):
                        _gather(c, c.get("path", ""))
            _gather(file_tree)
            
        has_package_json = any(f.endswith("package.json") for f in files)
        has_html = any(f.endswith(".html") for f in files)
        has_js_ts = any(f.endswith(".js") or f.endswith(".ts") or f.endswith(".jsx") or f.endswith(".tsx") for f in files)
        has_css = any(f.endswith(".css") or f.endswith(".scss") for f in files)

        # Framework-specific markers
        has_vite = any("vite.config" in f for f in files)
        has_tailwind = any("tailwind.config" in f for f in files)
        
        # Determine specific project type
        if hint_type == "frontend-only" or (not hint_type and has_html and not has_package_json and not has_js_ts):
            # Static HTML or explicit frontend hint without package manager
            analysis.project_type = "static-html"
            analysis.frontend_info = {
                "detected": True,
                "framework": "static-html",
                "entry_point": "index.html" if any(f.endswith("index.html") for f in files) else (files[0] if files else "index.html")
            }
        elif hint_type == "backend-only" or (not hint_type and parsed_code and parsed_code.get("api_endpoints")):
            analysis.project_type = "backend-only"
            analysis.backend_info = {
                "detected": True,
                "language": "go" if any(f.endswith(".go") for f in files) else ("node" if has_js_ts else "python"),
                "package_manager": "go.mod" if any(f.endswith("go.mod") for f in files) else ("npm" if has_package_json else None)
            }
        elif hint_type == "fullstack" or (has_package_json and (has_html or has_js_ts)):
            analysis.project_type = "fullstack"
            analysis.frontend_info = {
                "detected": True, 
                "package_manager": "npm" if has_package_json else None,
                "framework": "vite" if has_vite else ("react" if any(".jsx" in f or ".tsx" in f for f in files) else "unknown")
            }
            analysis.backend_info = {
                "detected": True,
                "language": "node" if has_js_ts else "python"
            }
        else:
            # Absolute fallback
            analysis.project_type = "frontend-only"
            analysis.frontend_info = {
                "detected": True,
                "framework": "react" if has_package_json and any(".jsx" in f or ".tsx" in f for f in files) else "html"
            }

    # 4b. Post-process: fix common Node backend port mis-detections (e.g., default 3000).
    try:
        be = dict(analysis.backend_info or {})
        lang = str(be.get("language") or "").lower()

        # Some LLM analyses don't populate `detected`; treat presence of a backend_info as a signal.
        looks_like_node = lang in {"javascript", "typescript", "node"}
        if looks_like_node or be.get("framework") in {"express", "nestjs", "fastify", "koa", "hono"}:
            # Choose backend root by finding a package.json under common locations.
            candidates: list[tuple[Path, str]] = []
            rel_hint = str(be.get("path") or ".")
            if rel_hint and rel_hint != ".":
                candidates.append((root / rel_hint, rel_hint))
            candidates.extend([
                (root / "backend", "backend"),
                (root / "server", "server"),
                (root / "api", "api"),
                (root, "."),
            ])

            backend_root: Path | None = None
            backend_rel: str | None = None
            for p, rel in candidates:
                if (p / "package.json").exists():
                    backend_root = p
                    backend_rel = rel
                    break

            if backend_root:
                pkg_path = backend_root / "package.json"
                scripts: dict[str, str] = {}
                try:
                    pkg = json.loads(pkg_path.read_text(encoding="utf-8", errors="ignore"))
                    raw_scripts = pkg.get("scripts", {})
                    if isinstance(raw_scripts, dict):
                        scripts = {k: v for k, v in raw_scripts.items() if isinstance(v, str)}
                except Exception:
                    scripts = {}

                script_text = "\n".join(scripts.values())
                entry_candidates: list[str] = []
                entry_candidates.extend(re.findall(r"([\w./-]+\.(?:ts|js))", script_text))
                entry_candidates.extend([
                    "src/index.ts",
                    "src/server.ts",
                    "src/main.ts",
                    "src/index.js",
                    "index.ts",
                    "index.js",
                    "server.js",
                    "app.js",
                ])

                def _infer_port_from_text(text: str) -> int | None:
                    for pat in (
                        r"process\.env\.PORT\s*\|\|\s*(\d{2,5})",
                        r"\bport\s*[:=]\s*(\d{2,5})\b",
                        r"\.listen\(\s*(\d{2,5})\b",
                    ):
                        mm = re.search(pat, text)
                        if mm:
                            try:
                                return int(mm.group(1))
                            except Exception:
                                pass
                    return None

                inferred_port: int | None = None
                seen: set[str] = set()
                for rel_entry in entry_candidates:
                    if rel_entry in seen:
                        continue
                    seen.add(rel_entry)
                    p = backend_root / rel_entry
                    if not p.exists() or not p.is_file():
                        continue
                    try:
                        text = p.read_text(encoding="utf-8", errors="ignore")
                    except Exception:
                        continue
                    inferred_port = _infer_port_from_text(text)
                    if inferred_port:
                        break

                changed = False
                if backend_rel and backend_rel != be.get("path"):
                    be["path"] = backend_rel
                    changed = True

                if inferred_port and inferred_port != be.get("port"):
                    logger.info(
                        "Overriding Node backend port %s → %s based on source scan",
                        be.get("port"),
                        inferred_port,
                    )
                    be["port"] = inferred_port
                    changed = True

                if changed:
                    analysis.backend_info = be
    except Exception as exc:
        logger.warning("Node port override skipped: %s", exc)

    # 5. Merge code-parser results into analysis
    if parsed_code:
        # NOTE: code_parser.parse_project() already returns dicts (via asdict()),
        # NOT dataclass instances. Do NOT call asdict() on them again.
        analysis.api_endpoints = parsed_code.get("api_endpoints", [])
        analysis.ui_elements = parsed_code.get("ui_elements", [])
        analysis.summary_dict = parsed_code.get("summary", {})

        backend_info = dict(analysis.backend_info or {})
        # Prefer LLM-detected endpoints; fall back / augment with parsed ones
        if not backend_info.get("api_endpoints") and analysis.api_endpoints:
            backend_info["api_endpoints"] = analysis.api_endpoints
        # Always store the full code scan for legacy support
        backend_info["code_scan"] = {
            "api_endpoints": analysis.api_endpoints,
            "ui_elements": analysis.ui_elements,
            "components": parsed_code.get("components", []),
            "routes": parsed_code.get("routes", []),
            "summary": analysis.summary_dict,
        }
        analysis.backend_info = backend_info

    logger.info("analyze_project: returning analysis with %d api_endpoints", len(analysis.api_endpoints))
    return analysis
